-- Jazym seed data — generated by scripts/gen-seed-sql.mjs. Do not hand-edit.
-- Idempotent: re-running upserts by slug / wilaya. Add real product photos via
-- the admin (this seed sets no product_images rows).

begin;

-- categories --------------------------------------------------------
insert into public.categories (slug, name_fr, name_ar, description_fr, description_ar, sort_order) values ('cahiers', 'Cahiers de l''enseignant', 'دفاتر الأستاذ', 'Cahier journal, fiches, formation, séminaires — personnalisés à votre nom.', 'الدفتر اليومي، المذكرات، التكوين، الندوات — مخصّصة باسمك.', 1)
on conflict (slug) do update set name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar, sort_order=excluded.sort_order;
insert into public.categories (slug, name_fr, name_ar, description_fr, description_ar, sort_order) values ('accessoires', 'Accessoires & organisateurs', 'إكسسوارات ومنظّمات', 'Organisateurs de dossier, porte-mémoire, organisateur de tableau.', 'منظّمات الملفات، حافظة المذكرة، منظّمة السبورة.', 2)
on conflict (slug) do update set name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar, sort_order=excluded.sort_order;
insert into public.categories (slug, name_fr, name_ar, description_fr, description_ar, sort_order) values ('strategies', 'Stratégies pédagogiques', 'استراتيجيات بيداغوجية', 'Kits concrets pour animer la classe : pigeon voyageur, train de mots, théière…', 'حقائب عملية لتنشيط القسم: الحمام الزاجل، قطار الكلمات، إبريق الشاي…', 3)
on conflict (slug) do update set name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar, sort_order=excluded.sort_order;

-- products ---------------------------------------------------------
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('cahier-journal', 'Cahier journal', 'الدفتر اليومي', 'Le cahier journal quotidien de l''enseignant : une page par jour, repères de séances et de progression. Couverture personnalisée à votre nom et votre matière.', 'الدفتر اليومي للأستاذ: صفحة لكل يوم، مع معالم الحصص والتدرّج. غلاف مخصّص باسمك ومادّتك.', array['Papier 80 g anti-transparence','Reliure cousue résistante','Nom + matière imprimés sur la couverture','Format A4']::text[], array['ورق 80 غ غير شفّاف','تجليد مخيط متين','الاسم + المادة مطبوعان على الغلاف','قياس A4']::text[], 2200, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-001', '[]'::jsonb, '[]'::jsonb, '[{"name_fr":"Nombre de pages","name_ar":"عدد الصفحات","values":[{"value_fr":"120 pages","value_ar":"120 صفحة","image_url":null},{"value_fr":"160 pages","value_ar":"160 صفحة","image_url":null},{"value_fr":"200 pages","value_ar":"200 صفحة","image_url":null},{"value_fr":"300 pages","value_ar":"300 صفحة","image_url":null}]}]'::jsonb, '[]'::jsonb, true, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('cahier-de-notes', 'Cahier de notes', 'دفتر التنقيط', 'Cahier de notes et d''évaluation — grilles prêtes à remplir pour suivre les résultats de vos élèves sur toute l''année.', 'دفتر التنقيط والتقويم — جداول جاهزة للتعبئة لمتابعة نتائج تلاميذك طوال السنة.', array['60 pages quadrillées','Grilles de notes pré-imprimées','Couverture rigide personnalisée']::text[], array['60 صفحة مسطّرة','جداول تنقيط مطبوعة مسبقًا','غلاف صلب مخصّص']::text[], 1700, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-002', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('cahier-de-formation', 'Cahier de formation', 'دفتر التكوين', 'Pour consigner les journées de formation, les apports des inspecteurs et vos notes de perfectionnement.', 'لتدوين أيام التكوين، وملاحظات المفتشين، ومذكّراتك حول التطوير المهني.', array['Papier 80 g','Intercalaires par thème','Nom imprimé sur la couverture']::text[], array['ورق 80 غ','فواصل حسب المحور','الاسم مطبوع على الغلاف']::text[], 2200, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-003', '[]'::jsonb, '[]'::jsonb, '[{"name_fr":"Nombre de pages","name_ar":"عدد الصفحات","values":[{"value_fr":"120 pages","value_ar":"120 صفحة","image_url":null},{"value_fr":"160 pages","value_ar":"160 صفحة","image_url":null},{"value_fr":"200 pages","value_ar":"200 صفحة","image_url":null},{"value_fr":"300 pages","value_ar":"300 صفحة","image_url":null}]}]'::jsonb, '[]'::jsonb, true, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('cahier-de-seminaires', 'Cahier de séminaires', 'دفتر الندوات', 'Cahier dédié aux séminaires pédagogiques et aux comptes-rendus de réunions de coordination.', 'دفتر خاص بالندوات البيداغوجية ومحاضر اجتماعات التنسيق.', array['Papier 80 g','Pages numérotées','Couverture personnalisée']::text[], array['ورق 80 غ','صفحات مرقّمة','غلاف مخصّص']::text[], 2200, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-004', '[]'::jsonb, '[]'::jsonb, '[{"name_fr":"Nombre de pages","name_ar":"عدد الصفحات","values":[{"value_fr":"120 pages","value_ar":"120 صفحة","image_url":null},{"value_fr":"160 pages","value_ar":"160 صفحة","image_url":null},{"value_fr":"200 pages","value_ar":"200 صفحة","image_url":null},{"value_fr":"300 pages","value_ar":"300 صفحة","image_url":null}]}]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('cahier-de-fiches', 'Cahier de fiches (planning)', 'دفتر المذكرات (التخطيط)', 'Cahier de préparation des fiches de leçons : trame de séance, objectifs, déroulement et évaluation.', 'دفتر تحضير مذكّرات الدروس: هيكل الحصة، الأهداف، السيرورة والتقويم.', array['Trame de fiche pré-imprimée','Papier 80 g','Nom + niveau sur la couverture']::text[], array['هيكل مذكّرة مطبوع مسبقًا','ورق 80 غ','الاسم + المستوى على الغلاف']::text[], 2200, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-005', '[]'::jsonb, '[]'::jsonb, '[{"name_fr":"Nombre de pages","name_ar":"عدد الصفحات","values":[{"value_fr":"120 pages","value_ar":"120 صفحة","image_url":null},{"value_fr":"160 pages","value_ar":"160 صفحة","image_url":null},{"value_fr":"200 pages","value_ar":"200 صفحة","image_url":null},{"value_fr":"300 pages","value_ar":"300 صفحة","image_url":null}]}]'::jsonb, '[]'::jsonb, true, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('cahier-de-remediation', 'Cahier de remédiation', 'دفتر المعالجة', 'Pour planifier et suivre les séances de remédiation : difficultés repérées, actions, progrès.', 'لتخطيط ومتابعة حصص المعالجة: الصعوبات المرصودة، الإجراءات، التقدّم.', array['Grilles de suivi individuel','Papier 80 g','Couverture personnalisée']::text[], array['جداول متابعة فردية','ورق 80 غ','غلاف مخصّص']::text[], 2200, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-006', '[]'::jsonb, '[]'::jsonb, '[{"name_fr":"Nombre de pages","name_ar":"عدد الصفحات","values":[{"value_fr":"120 pages","value_ar":"120 صفحة","image_url":null},{"value_fr":"160 pages","value_ar":"160 صفحة","image_url":null}]}]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('registre-appel', 'Registre d''appel', 'دفتر المناداة', 'Registre d''appel et de présence — mise en page claire, une classe par double-page.', 'دفتر المناداة والحضور — تصميم واضح، قسم واحد في كل صفحتين متقابلتين.', array['40 pages','Colonnes de présence pré-imprimées','Couverture rigide']::text[], array['40 صفحة','أعمدة حضور مطبوعة مسبقًا','غلاف صلب']::text[], 1400, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-007', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('cahier-de-roulement', 'Cahier de roulement', 'دفتر التداول', 'Cahier de roulement pour la circulation de l''information entre enseignants et administration.', 'دفتر التداول لتمرير المعلومة بين الأساتذة والإدارة.', array['Papier 70 g','Pages lignées','Couverture personnalisée']::text[], array['ورق 70 غ','صفحات مسطّرة','غلاف مخصّص']::text[], 1700, null, (select id from public.categories where slug = 'cahiers'), 120, 'JZ-008', '[]'::jsonb, '[]'::jsonb, '[{"name_fr":"Nombre de pages","name_ar":"عدد الصفحات","values":[{"value_fr":"120 pages","value_ar":"120 صفحة","image_url":null},{"value_fr":"160 pages","value_ar":"160 صفحة","image_url":null}]}]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('organisateur-titularisation', 'Organisateur — comité de titularisation', 'منظّمات لجنة التثبيت', 'Intercalaires et organisateur de dossier pour le comité de titularisation, personnalisés selon la fonction.', 'فواصل ومنظّم ملف للجنة التثبيت، مخصّصة حسب الوظيفة.', array['Jeu d''intercalaires','Étiquettes de fonction','Format A4']::text[], array['مجموعة فواصل','بطاقات الوظيفة','قياس A4']::text[], 250, null, (select id from public.categories where slug = 'accessoires'), 120, 'JZ-009', '[]'::jsonb, '[]'::jsonb, '[{"name_fr":"Fonction","name_ar":"الوظيفة","values":[{"value_fr":"Enseignant(e)","value_ar":"الأستاذ(ة)","image_url":null},{"value_fr":"Inspecteur(trice)","value_ar":"المفتّش(ة)","image_url":null},{"value_fr":"Directeur(trice)","value_ar":"المدير(ة)","image_url":null}]}]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('porte-memoire-titularisation', 'Porte-mémoire de titularisation', 'حافظة مذكرة التثبيت', 'Chemise rigide pour présenter et protéger la mémoire de titularisation.', 'حافظة صلبة لتقديم وحماية مذكّرة التثبيت.', array['Carton rigide plastifié','Fenêtre titre personnalisable','Format A4']::text[], array['كرتون صلب مغلّف','نافذة عنوان قابلة للتخصيص','قياس A4']::text[], 300, null, (select id from public.categories where slug = 'accessoires'), 120, 'JZ-010', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('organisateur-tableau', 'Organisateur de tableau', 'منظّمة السبورة', 'Pochette murale pour garder feutres, brosse et fiches à portée du tableau.', 'جيب جداري للحفاظ على الأقلام، الممحاة والبطاقات قرب السبورة.', array['Tissu enduit lavable','3 compartiments','Fixation adhésive + œillets']::text[], array['قماش مطلي قابل للغسل','3 جيوب','تثبيت لاصق + حلقات']::text[], 250, null, (select id from public.categories where slug = 'accessoires'), 120, 'JZ-011', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('strategie-pigeon-voyageur', 'Stratégie du pigeon voyageur', 'استراتيجية الحمام الزاجل', 'Kit « pigeon voyageur » (5 pigeons) pour faire circuler consignes et messages entre groupes de la classe de façon ludique.', 'حقيبة «الحمام الزاجل» (5 حمامات) لتمرير التعليمات والرسائل بين مجموعات القسم بطريقة ممتعة.', array['5 pigeons cartonnés plastifiés','Porte-messages','Guide d''utilisation en classe']::text[], array['5 حمامات من الكرتون المغلّف','حاملات رسائل','دليل الاستعمال في القسم']::text[], 1200, null, (select id from public.categories where slug = 'strategies'), 120, 'JZ-012', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, true, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('strategie-autre-moitie', 'Stratégie de l''autre moitié', 'استراتيجية النصف الآخر', 'Kit « l''autre moitié » (4 œufs) : chaque élève cherche la moitié complémentaire — parfait pour les appariements et le vocabulaire.', 'حقيبة «النصف الآخر» (4 بيضات): كل تلميذ يبحث عن النصف المكمّل — مثالية للمزاوجة والمفردات.', array['4 œufs sécables','Jeux de cartes à apparier','Fiches enseignant']::text[], array['4 بيضات قابلة للفصل','بطاقات للمزاوجة','بطاقات للأستاذ']::text[], 1000, null, (select id from public.categories where slug = 'strategies'), 120, 'JZ-013', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('strategie-train-de-mots', 'Stratégie du train de mots', 'استراتيجية قطار الكلمات', 'Kit « train de mots » (4 wagons + remorque) pour construire phrases, ordres de mots et suites logiques.', 'حقيبة «قطار الكلمات» (4 عربات + مقطورة) لبناء الجُمل، ترتيب الكلمات والمتتاليات المنطقية.', array['Locomotive + 4 wagons + remorque','Étiquettes effaçables','Guide d''activités']::text[], array['قاطرة + 4 عربات + مقطورة','بطاقات قابلة للمسح','دليل أنشطة']::text[], 1000, null, (select id from public.categories where slug = 'strategies'), 120, 'JZ-014', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, true, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('strategie-theiere', 'Stratégie de la théière', 'استراتيجية إبريق الشاي', 'Kit « théière » (1 théière + 6 verres) : la théière pose la question, chaque verre reçoit une réponse d''élève.', 'حقيبة «إبريق الشاي» (إبريق + 6 كؤوس): الإبريق يطرح السؤال، وكل كأس يستقبل إجابة تلميذ.', array['1 théière + 6 verres cartonnés','Cartes questions/réponses','Guide']::text[], array['إبريق + 6 كؤوس كرتونية','بطاقات أسئلة/أجوبة','دليل']::text[], 800, null, (select id from public.categories where slug = 'strategies'), 120, 'JZ-015', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('strategie-cadenas-cle', 'Stratégie du cadenas et de la clé', 'استراتيجية القفل والمفتاح', 'Kit « cadenas & clé » (4 clés + 4 cadenas) : associer la bonne clé (réponse) au bon cadenas (question).', 'حقيبة «القفل والمفتاح» (4 مفاتيح + 4 أقفال): مطابقة المفتاح الصحيح (الإجابة) بالقفل المناسب (السؤال).', array['4 cadenas + 4 clés cartonnés','Cartes à associer','Fiches enseignant']::text[], array['4 أقفال + 4 مفاتيح كرتونية','بطاقات للمطابقة','بطاقات للأستاذ']::text[], 1200, null, (select id from public.categories where slug = 'strategies'), 120, 'JZ-016', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('strategie-cinq-doigts', 'Stratégie des cinq doigts', 'استراتيجية الأصابع الخمسة', 'Kit « cinq doigts » pour structurer un rappel, un résumé ou une auto-évaluation en cinq points.', 'حقيبة «الأصابع الخمسة» لهيكلة تذكير أو تلخيص أو تقويم ذاتي في خمس نقاط.', array['Main géante + 5 doigts amovibles','Pictogrammes de consignes','Guide']::text[], array['يد كبيرة + 5 أصابع قابلة للنزع','رموز التعليمات','دليل']::text[], 700, null, (select id from public.categories where slug = 'strategies'), 120, 'JZ-017', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;
insert into public.products
  (slug, name_fr, name_ar, description_fr, description_ar, details_fr, details_ar,
   price, compare_at_price, category_id, stock, style_code, colors, sizes, variants,
   quantity_offers, featured, status)
values ('strategie-pop-corn', 'Stratégie du pop-corn', 'استراتيجية الفشار', 'Kit « pop-corn » pour la prise de parole aléatoire : on tire un grain, l''élève répond.', 'حقيبة «الفشار» لأخذ الكلمة عشوائيًا: نسحب حبّة، والتلميذ يجيب.', array['Boîte + 30 grains nominatifs','Cartes défis','Guide d''animation']::text[], array['علبة + 30 حبّة بالأسماء','بطاقات تحدّيات','دليل التنشيط']::text[], 1000, null, (select id from public.categories where slug = 'strategies'), 120, 'JZ-018', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, 'active')
on conflict (slug) do update set
  name_fr=excluded.name_fr, name_ar=excluded.name_ar,
  description_fr=excluded.description_fr, description_ar=excluded.description_ar,
  details_fr=excluded.details_fr, details_ar=excluded.details_ar,
  price=excluded.price, compare_at_price=excluded.compare_at_price,
  category_id=excluded.category_id, stock=excluded.stock, style_code=excluded.style_code,
  colors=excluded.colors, sizes=excluded.sizes, variants=excluded.variants,
  quantity_offers=excluded.quantity_offers, featured=excluded.featured, status=excluded.status;

-- delivery prices (69 wilayas) -----------------------------------
insert into public.delivery_prices (wilaya, home_price, office_price)
select w.name,
       case when w.code <= 48 then 500 else 800 end,
       case when w.code <= 48 then 300 else 500 end
from (values
  (1, 'Adrar'),
  (2, 'Chlef'),
  (3, 'Laghouat'),
  (4, 'Oum El Bouaghi'),
  (5, 'Batna'),
  (6, 'Béjaïa'),
  (7, 'Biskra'),
  (8, 'Béchar'),
  (9, 'Blida'),
  (10, 'Bouira'),
  (11, 'Tamanrasset'),
  (12, 'Tébessa'),
  (13, 'Tlemcen'),
  (14, 'Tiaret'),
  (15, 'Tizi Ouzou'),
  (16, 'Alger'),
  (17, 'Djelfa'),
  (18, 'Jijel'),
  (19, 'Sétif'),
  (20, 'Saïda'),
  (21, 'Skikda'),
  (22, 'Sidi Bel Abbès'),
  (23, 'Annaba'),
  (24, 'Guelma'),
  (25, 'Constantine'),
  (26, 'Médéa'),
  (27, 'Mostaganem'),
  (28, 'M''Sila'),
  (29, 'Mascara'),
  (30, 'Ouargla'),
  (31, 'Oran'),
  (32, 'El Bayadh'),
  (33, 'Illizi'),
  (34, 'Bordj Bou Arréridj'),
  (35, 'Boumerdès'),
  (36, 'El Tarf'),
  (37, 'Tindouf'),
  (38, 'Tissemsilt'),
  (39, 'El Oued'),
  (40, 'Khenchela'),
  (41, 'Souk Ahras'),
  (42, 'Tipaza'),
  (43, 'Mila'),
  (44, 'Aïn Defla'),
  (45, 'Naâma'),
  (46, 'Aïn Témouchent'),
  (47, 'Ghardaïa'),
  (48, 'Relizane'),
  (49, 'Timimoun'),
  (50, 'Bordj Badji Mokhtar'),
  (51, 'Ouled Djellal'),
  (52, 'Béni Abbès'),
  (53, 'In Salah'),
  (54, 'In Guezzam'),
  (55, 'Touggourt'),
  (56, 'Djanet'),
  (57, 'El M''Ghair'),
  (58, 'El Meniaa'),
  (59, 'Aflou'),
  (60, 'Barika'),
  (61, 'El Kantara'),
  (62, 'Bir El Ater'),
  (63, 'El Aricha'),
  (64, 'Ksar Chellala'),
  (65, 'Aïn Oussera'),
  (66, 'Messaad'),
  (67, 'Ksar El Boukhari'),
  (68, 'Bou Saâda'),
  (69, 'El Abiodh Sidi Cheikh')
) as w(code, name)
on conflict (wilaya) do nothing;

-- reviews ---------------------------------------------------------
insert into public.client_reviews (client_name, stars, review_text, active) values ('Nadia B. — Enseignante primaire, Blida', 5, 'Le cahier journal est superbe, papier épais et mon nom imprimé proprement. Livré en 3 jours à Blida.', true);
insert into public.client_reviews (client_name, stars, review_text, active) values ('Karim L. — Professeur de maths, Oran', 5, 'J''ai commandé le pack fiches + formation. Qualité au rendez-vous et paiement à la livraison, rien à dire.', true);
insert into public.client_reviews (client_name, stars, review_text, active) values ('Samira K. — Directrice d''école, Sétif', 4, 'Les organisateurs de titularisation ont fait gagner un temps fou au comité. Je recommande.', true);
insert into public.client_reviews (client_name, stars, review_text, active) values ('Yacine M. — Enseignant CEM, Alger', 5, 'Les kits de stratégies changent l''ambiance de la classe. Le train de mots est un carton avec mes 1AM.', true);

-- store settings ------------------------------------------------
update public.store_settings set
  announcement_fr = 'Livraison partout en Algérie · Paiement à la livraison',
  announcement_ar = 'توصيل إلى كامل الوطن · الدفع عند الاستلام'
where id = 1;

commit;
